name: build python module

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Get Github action IP
      id: ip
      uses: haythem/public-ip@v1.2

    - name: Setting environment variables..
      run: |
        echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV
        echo "AWS_SG_NAME=sg-123456" >> $GITHUB_ENV
        
    - name: Add Github Actions IP to Security group
      run: |
        aws ec2 authorize-security-group-ingress --group-id ${{ env.AWS_SG_NAME }} --protocol tcp --port 80 --cidr ${{ steps.ip.outputs.ipv4 }}/32    
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}      
    
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Bump version up in setup.py
      run: |
        sed -i "7c\\VERSION = \"1.${{ github.run_number }}\"" setup.py
        git config user.email "it@org.com"
        git config user.name "ORG"
        git add setup.py
        git commit -m "[skip ci] Updating version in setup.py [automated]"
        git push
        
    - name: Install dependencies and etc
      run: |
        python -m pip install --upgrade pip setuptools wheel     
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        make 
#        let's just make all
#        make deploy
