name: GW CODE DEPLOY and REFRESH
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest    
    environment: production1
    steps:

    - name: Authorize SSH Connections
      uses: mnavarrocarter/authorize-aws-security-group-ingress-action@v1.0.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}   
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1' # Your AWS region
        aws-security-group-id: ${{ secrets.AWS_SSH_SECURITY_GROUP_ID }}
        protocol: 'tcp'
        port: 22
        
    - uses: actions/checkout@v4
    - name: copy files!
      uses: appleboy/scp-action@v0.1.4
      with:
        host: api1.org.com
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        port: 22
        source: production-gateway.js
        target: /home/ubuntu
        
    - name: Runs a command inside the instance
      uses: appleboy/ssh-action@v0.1.10
      with:
#    host: ${{ secrets.SSH_HOST }}
        host: api1.org.com
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: | 
         sudo mv /home/ubuntu/production-gateway.js /var/www/html/gateway.js 
         /home/ubuntu/refresh.sh
#refresh script cycles PM2 on the gateway host!
